apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: mongodb
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
    - port: 443
      targetPort: 8443
      nodePort: 30443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: tls
              mountPath: /etc/nginx/ssl
              readOnly: true
        - name: mongo-express
          image: mongo-express
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: "mongodb"
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: "admin"
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: "admin"
          ports:
            - containerPort: 8081
      volumes:
        - name: nginx-config
          configMap:
            name: mongo-nginx-conf
        - name: tls
          secret:
            secretName: mongo-tls
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-nginx-conf
  namespace: mongodb
data:
  default.conf: |
    server {
      listen 8443 ssl;
      ssl_certificate /etc/nginx/ssl/tls.crt;
      ssl_certificate_key /etc/nginx/ssl/tls.key;

      location / {
        proxy_pass http://localhost:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
    }
