---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminmongo
  namespace: mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminmongo
  template:
    metadata:
      labels:
        app: adminmongo
    spec:
      containers:
        - name: adminmongo
          image: mrvautin/adminmongo
          ports:
            - containerPort: 1234
          env:
            - name: CONN_NAME
              value: "MongoDB"
            - name: DB_HOST
              value: "mongodb://admin:admin123@mongodb-service:27017/admin"
---
apiVersion: v1
kind: Service
metadata:
  name: adminmongo-service
  namespace: mongo-app
spec:
  type: NodePort
  selector:
    app: adminmongo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1234
      nodePort: 30080  # facultatif : sinon, K8s en choisira un automatiquement (dans la plage 30000–32767)

