apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminmongo
  namespace: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminmongo
  template:
    metadata:
      labels:
        app: adminmongo
    spec:
      containers:
      - name: adminmongo
        image: mrvautin/adminmongo
        env:
        - name: CONNECTIONS
          value: '[{"name":"Local","connection_string":"mongodb://adminuser:adminpass@mongodb:27017"}]'
        ports:
        - containerPort: 1234
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 443
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        - name: certs
          mountPath: /etc/nginx/certs
      volumes:
      - name: nginx-conf
        configMap:
          name: adminmongo-nginx
      - name: certs
        secret:
          secretName: mongo-tls
---
apiVersion: v1
kind: Service
metadata:
  name: adminmongo
  namespace: mongodb
spec:
  type: NodePort
  selector:
    app: adminmongo
  ports:
  - name: https
    port: 443
    targetPort: 443
    nodePort: 32433
