apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-ui
  namespace: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-ui
  template:
    metadata:
      labels:
        app: mongo-ui
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: "mongodb"
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: "adminuser"
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: "adminpass"
        ports:
        - containerPort: 8081
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 443
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        - name: certs
          mountPath: /etc/nginx/certs
      volumes:
      - name: nginx-conf
        configMap:
          name: mongo-ui-nginx
      - name: certs
        secret:
          secretName: mongo-tls
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-ui
  namespace: mongodb
spec:
  selector:
    app: mongo-ui
  type: NodePort
  ports:
  - name: https
    port: 443
    targetPort: 443
    nodePort: 32433
